#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryIE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iExcipient")]
	public partial class KetnoiCSDLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertd_Chucnang(d_Chucnang instance);
    partial void Updated_Chucnang(d_Chucnang instance);
    partial void Deleted_Chucnang(d_Chucnang instance);
    partial void Insertr_Thanhphan_EWGScore(r_Thanhphan_EWGScore instance);
    partial void Updater_Thanhphan_EWGScore(r_Thanhphan_EWGScore instance);
    partial void Deleter_Thanhphan_EWGScore(r_Thanhphan_EWGScore instance);
    partial void Insertd_Dangbaoche(d_Dangbaoche instance);
    partial void Updated_Dangbaoche(d_Dangbaoche instance);
    partial void Deleted_Dangbaoche(d_Dangbaoche instance);
    partial void Insertd_Quydinh(d_Quydinh instance);
    partial void Updated_Quydinh(d_Quydinh instance);
    partial void Deleted_Quydinh(d_Quydinh instance);
    partial void Insertd_Thanhphan(d_Thanhphan instance);
    partial void Updated_Thanhphan(d_Thanhphan instance);
    partial void Deleted_Thanhphan(d_Thanhphan instance);
    partial void Insertr_Chatlienquan(r_Chatlienquan instance);
    partial void Updater_Chatlienquan(r_Chatlienquan instance);
    partial void Deleter_Chatlienquan(r_Chatlienquan instance);
    partial void Insertr_Thanhphan_Chucnang(r_Thanhphan_Chucnang instance);
    partial void Updater_Thanhphan_Chucnang(r_Thanhphan_Chucnang instance);
    partial void Deleter_Thanhphan_Chucnang(r_Thanhphan_Chucnang instance);
    partial void Insertr_Thanhphan_Dangbaoche(r_Thanhphan_Dangbaoche instance);
    partial void Updater_Thanhphan_Dangbaoche(r_Thanhphan_Dangbaoche instance);
    partial void Deleter_Thanhphan_Dangbaoche(r_Thanhphan_Dangbaoche instance);
    #endregion
		
		public KetnoiCSDLDataContext() : 
				base(global::ClassLibraryIE.Properties.Settings.Default.iExcipientConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public KetnoiCSDLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KetnoiCSDLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KetnoiCSDLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KetnoiCSDLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<d_Chucnang> d_Chucnangs
		{
			get
			{
				return this.GetTable<d_Chucnang>();
			}
		}
		
		public System.Data.Linq.Table<r_Thanhphan_EWGScore> r_Thanhphan_EWGScores
		{
			get
			{
				return this.GetTable<r_Thanhphan_EWGScore>();
			}
		}
		
		public System.Data.Linq.Table<d_Dangbaoche> d_Dangbaoches
		{
			get
			{
				return this.GetTable<d_Dangbaoche>();
			}
		}
		
		public System.Data.Linq.Table<d_Quydinh> d_Quydinhs
		{
			get
			{
				return this.GetTable<d_Quydinh>();
			}
		}
		
		public System.Data.Linq.Table<d_Thanhphan> d_Thanhphans
		{
			get
			{
				return this.GetTable<d_Thanhphan>();
			}
		}
		
		public System.Data.Linq.Table<r_Chatlienquan> r_Chatlienquans
		{
			get
			{
				return this.GetTable<r_Chatlienquan>();
			}
		}
		
		public System.Data.Linq.Table<r_Thanhphan_Chucnang> r_Thanhphan_Chucnangs
		{
			get
			{
				return this.GetTable<r_Thanhphan_Chucnang>();
			}
		}
		
		public System.Data.Linq.Table<r_Thanhphan_Dangbaoche> r_Thanhphan_Dangbaoches
		{
			get
			{
				return this.GetTable<r_Thanhphan_Dangbaoche>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_Chucnang")]
	public partial class d_Chucnang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDChucnang;
		
		private string _Tenchucnang;
		
		private string _Motachucnang;
		
		private EntitySet<r_Thanhphan_Chucnang> _r_Thanhphan_Chucnangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChucnangChanging(int value);
    partial void OnIDChucnangChanged();
    partial void OnTenchucnangChanging(string value);
    partial void OnTenchucnangChanged();
    partial void OnMotachucnangChanging(string value);
    partial void OnMotachucnangChanged();
    #endregion
		
		public d_Chucnang()
		{
			this._r_Thanhphan_Chucnangs = new EntitySet<r_Thanhphan_Chucnang>(new Action<r_Thanhphan_Chucnang>(this.attach_r_Thanhphan_Chucnangs), new Action<r_Thanhphan_Chucnang>(this.detach_r_Thanhphan_Chucnangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChucnang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDChucnang
		{
			get
			{
				return this._IDChucnang;
			}
			set
			{
				if ((this._IDChucnang != value))
				{
					this.OnIDChucnangChanging(value);
					this.SendPropertyChanging();
					this._IDChucnang = value;
					this.SendPropertyChanged("IDChucnang");
					this.OnIDChucnangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenchucnang", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Tenchucnang
		{
			get
			{
				return this._Tenchucnang;
			}
			set
			{
				if ((this._Tenchucnang != value))
				{
					this.OnTenchucnangChanging(value);
					this.SendPropertyChanging();
					this._Tenchucnang = value;
					this.SendPropertyChanged("Tenchucnang");
					this.OnTenchucnangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motachucnang", DbType="NVarChar(500)")]
		public string Motachucnang
		{
			get
			{
				return this._Motachucnang;
			}
			set
			{
				if ((this._Motachucnang != value))
				{
					this.OnMotachucnangChanging(value);
					this.SendPropertyChanging();
					this._Motachucnang = value;
					this.SendPropertyChanged("Motachucnang");
					this.OnMotachucnangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Chucnang_r_Thanhphan_Chucnang", Storage="_r_Thanhphan_Chucnangs", ThisKey="IDChucnang", OtherKey="IDChucnang")]
		public EntitySet<r_Thanhphan_Chucnang> r_Thanhphan_Chucnangs
		{
			get
			{
				return this._r_Thanhphan_Chucnangs;
			}
			set
			{
				this._r_Thanhphan_Chucnangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_r_Thanhphan_Chucnangs(r_Thanhphan_Chucnang entity)
		{
			this.SendPropertyChanging();
			entity.d_Chucnang = this;
		}
		
		private void detach_r_Thanhphan_Chucnangs(r_Thanhphan_Chucnang entity)
		{
			this.SendPropertyChanging();
			entity.d_Chucnang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.r_Thanhphan_EWGScore")]
	public partial class r_Thanhphan_EWGScore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDEWGScore;
		
		private int _IDThanhphan;
		
		private System.Nullable<int> _EWG_Score_from;
		
		private System.Nullable<int> _EWG_Score_to;
		
		private string _EWG_Score;
		
		private string _EWG_DataAvailability;
		
		private EntityRef<d_Thanhphan> _d_Thanhphan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDEWGScoreChanging(int value);
    partial void OnIDEWGScoreChanged();
    partial void OnIDThanhphanChanging(int value);
    partial void OnIDThanhphanChanged();
    partial void OnEWG_Score_fromChanging(System.Nullable<int> value);
    partial void OnEWG_Score_fromChanged();
    partial void OnEWG_Score_toChanging(System.Nullable<int> value);
    partial void OnEWG_Score_toChanged();
    partial void OnEWG_ScoreChanging(string value);
    partial void OnEWG_ScoreChanged();
    partial void OnEWG_DataAvailabilityChanging(string value);
    partial void OnEWG_DataAvailabilityChanged();
    #endregion
		
		public r_Thanhphan_EWGScore()
		{
			this._d_Thanhphan = default(EntityRef<d_Thanhphan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEWGScore", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDEWGScore
		{
			get
			{
				return this._IDEWGScore;
			}
			set
			{
				if ((this._IDEWGScore != value))
				{
					this.OnIDEWGScoreChanging(value);
					this.SendPropertyChanging();
					this._IDEWGScore = value;
					this.SendPropertyChanged("IDEWGScore");
					this.OnIDEWGScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphan", DbType="Int NOT NULL")]
		public int IDThanhphan
		{
			get
			{
				return this._IDThanhphan;
			}
			set
			{
				if ((this._IDThanhphan != value))
				{
					if (this._d_Thanhphan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDThanhphanChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphan = value;
					this.SendPropertyChanged("IDThanhphan");
					this.OnIDThanhphanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EWG_Score_from", DbType="Int")]
		public System.Nullable<int> EWG_Score_from
		{
			get
			{
				return this._EWG_Score_from;
			}
			set
			{
				if ((this._EWG_Score_from != value))
				{
					this.OnEWG_Score_fromChanging(value);
					this.SendPropertyChanging();
					this._EWG_Score_from = value;
					this.SendPropertyChanged("EWG_Score_from");
					this.OnEWG_Score_fromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EWG_Score_to", DbType="Int")]
		public System.Nullable<int> EWG_Score_to
		{
			get
			{
				return this._EWG_Score_to;
			}
			set
			{
				if ((this._EWG_Score_to != value))
				{
					this.OnEWG_Score_toChanging(value);
					this.SendPropertyChanging();
					this._EWG_Score_to = value;
					this.SendPropertyChanged("EWG_Score_to");
					this.OnEWG_Score_toChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EWG_Score", DbType="NVarChar(100)")]
		public string EWG_Score
		{
			get
			{
				return this._EWG_Score;
			}
			set
			{
				if ((this._EWG_Score != value))
				{
					this.OnEWG_ScoreChanging(value);
					this.SendPropertyChanging();
					this._EWG_Score = value;
					this.SendPropertyChanged("EWG_Score");
					this.OnEWG_ScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EWG_DataAvailability", DbType="NVarChar(100)")]
		public string EWG_DataAvailability
		{
			get
			{
				return this._EWG_DataAvailability;
			}
			set
			{
				if ((this._EWG_DataAvailability != value))
				{
					this.OnEWG_DataAvailabilityChanging(value);
					this.SendPropertyChanging();
					this._EWG_DataAvailability = value;
					this.SendPropertyChanged("EWG_DataAvailability");
					this.OnEWG_DataAvailabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_r_Thanhphan_EWGScore", Storage="_d_Thanhphan", ThisKey="IDThanhphan", OtherKey="IDThanhphan", IsForeignKey=true)]
		public d_Thanhphan d_Thanhphan
		{
			get
			{
				return this._d_Thanhphan.Entity;
			}
			set
			{
				d_Thanhphan previousValue = this._d_Thanhphan.Entity;
				if (((previousValue != value) 
							|| (this._d_Thanhphan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Thanhphan.Entity = null;
						previousValue.r_Thanhphan_EWGScores.Remove(this);
					}
					this._d_Thanhphan.Entity = value;
					if ((value != null))
					{
						value.r_Thanhphan_EWGScores.Add(this);
						this._IDThanhphan = value.IDThanhphan;
					}
					else
					{
						this._IDThanhphan = default(int);
					}
					this.SendPropertyChanged("d_Thanhphan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_Dangbaoche")]
	public partial class d_Dangbaoche : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDangbaoche;
		
		private string _TenDangbaoche;
		
		private EntitySet<r_Thanhphan_Dangbaoche> _r_Thanhphan_Dangbaoches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDangbaocheChanging(int value);
    partial void OnIDDangbaocheChanged();
    partial void OnTenDangbaocheChanging(string value);
    partial void OnTenDangbaocheChanged();
    #endregion
		
		public d_Dangbaoche()
		{
			this._r_Thanhphan_Dangbaoches = new EntitySet<r_Thanhphan_Dangbaoche>(new Action<r_Thanhphan_Dangbaoche>(this.attach_r_Thanhphan_Dangbaoches), new Action<r_Thanhphan_Dangbaoche>(this.detach_r_Thanhphan_Dangbaoches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDangbaoche", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDangbaoche
		{
			get
			{
				return this._IDDangbaoche;
			}
			set
			{
				if ((this._IDDangbaoche != value))
				{
					this.OnIDDangbaocheChanging(value);
					this.SendPropertyChanging();
					this._IDDangbaoche = value;
					this.SendPropertyChanged("IDDangbaoche");
					this.OnIDDangbaocheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangbaoche", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string TenDangbaoche
		{
			get
			{
				return this._TenDangbaoche;
			}
			set
			{
				if ((this._TenDangbaoche != value))
				{
					this.OnTenDangbaocheChanging(value);
					this.SendPropertyChanging();
					this._TenDangbaoche = value;
					this.SendPropertyChanged("TenDangbaoche");
					this.OnTenDangbaocheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Dangbaoche_r_Thanhphan_Dangbaoche", Storage="_r_Thanhphan_Dangbaoches", ThisKey="IDDangbaoche", OtherKey="IDDangbaoche")]
		public EntitySet<r_Thanhphan_Dangbaoche> r_Thanhphan_Dangbaoches
		{
			get
			{
				return this._r_Thanhphan_Dangbaoches;
			}
			set
			{
				this._r_Thanhphan_Dangbaoches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_r_Thanhphan_Dangbaoches(r_Thanhphan_Dangbaoche entity)
		{
			this.SendPropertyChanging();
			entity.d_Dangbaoche = this;
		}
		
		private void detach_r_Thanhphan_Dangbaoches(r_Thanhphan_Dangbaoche entity)
		{
			this.SendPropertyChanging();
			entity.d_Dangbaoche = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_Quydinh")]
	public partial class d_Quydinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDQuydinh;
		
		private int _IDThanhphan;
		
		private System.Nullable<bool> _AnnexII;
		
		private System.Nullable<bool> _AnnexIII;
		
		private System.Nullable<bool> _AnnexIV;
		
		private System.Nullable<bool> _AnnexV;
		
		private System.Nullable<bool> _AnnexVI;
		
		private string _DieuKienSuDung;
		
		private string _Ghichu;
		
		private EntityRef<d_Thanhphan> _d_Thanhphan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDQuydinhChanging(int value);
    partial void OnIDQuydinhChanged();
    partial void OnIDThanhphanChanging(int value);
    partial void OnIDThanhphanChanged();
    partial void OnAnnexIIChanging(System.Nullable<bool> value);
    partial void OnAnnexIIChanged();
    partial void OnAnnexIIIChanging(System.Nullable<bool> value);
    partial void OnAnnexIIIChanged();
    partial void OnAnnexIVChanging(System.Nullable<bool> value);
    partial void OnAnnexIVChanged();
    partial void OnAnnexVChanging(System.Nullable<bool> value);
    partial void OnAnnexVChanged();
    partial void OnAnnexVIChanging(System.Nullable<bool> value);
    partial void OnAnnexVIChanged();
    partial void OnDieuKienSuDungChanging(string value);
    partial void OnDieuKienSuDungChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    #endregion
		
		public d_Quydinh()
		{
			this._d_Thanhphan = default(EntityRef<d_Thanhphan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuydinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDQuydinh
		{
			get
			{
				return this._IDQuydinh;
			}
			set
			{
				if ((this._IDQuydinh != value))
				{
					this.OnIDQuydinhChanging(value);
					this.SendPropertyChanging();
					this._IDQuydinh = value;
					this.SendPropertyChanged("IDQuydinh");
					this.OnIDQuydinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphan", DbType="Int NOT NULL")]
		public int IDThanhphan
		{
			get
			{
				return this._IDThanhphan;
			}
			set
			{
				if ((this._IDThanhphan != value))
				{
					if (this._d_Thanhphan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDThanhphanChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphan = value;
					this.SendPropertyChanged("IDThanhphan");
					this.OnIDThanhphanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnexII", DbType="Bit")]
		public System.Nullable<bool> AnnexII
		{
			get
			{
				return this._AnnexII;
			}
			set
			{
				if ((this._AnnexII != value))
				{
					this.OnAnnexIIChanging(value);
					this.SendPropertyChanging();
					this._AnnexII = value;
					this.SendPropertyChanged("AnnexII");
					this.OnAnnexIIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnexIII", DbType="Bit")]
		public System.Nullable<bool> AnnexIII
		{
			get
			{
				return this._AnnexIII;
			}
			set
			{
				if ((this._AnnexIII != value))
				{
					this.OnAnnexIIIChanging(value);
					this.SendPropertyChanging();
					this._AnnexIII = value;
					this.SendPropertyChanged("AnnexIII");
					this.OnAnnexIIIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnexIV", DbType="Bit")]
		public System.Nullable<bool> AnnexIV
		{
			get
			{
				return this._AnnexIV;
			}
			set
			{
				if ((this._AnnexIV != value))
				{
					this.OnAnnexIVChanging(value);
					this.SendPropertyChanging();
					this._AnnexIV = value;
					this.SendPropertyChanged("AnnexIV");
					this.OnAnnexIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnexV", DbType="Bit")]
		public System.Nullable<bool> AnnexV
		{
			get
			{
				return this._AnnexV;
			}
			set
			{
				if ((this._AnnexV != value))
				{
					this.OnAnnexVChanging(value);
					this.SendPropertyChanging();
					this._AnnexV = value;
					this.SendPropertyChanged("AnnexV");
					this.OnAnnexVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnexVI", DbType="Bit")]
		public System.Nullable<bool> AnnexVI
		{
			get
			{
				return this._AnnexVI;
			}
			set
			{
				if ((this._AnnexVI != value))
				{
					this.OnAnnexVIChanging(value);
					this.SendPropertyChanging();
					this._AnnexVI = value;
					this.SendPropertyChanged("AnnexVI");
					this.OnAnnexVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DieuKienSuDung", DbType="NVarChar(2000)")]
		public string DieuKienSuDung
		{
			get
			{
				return this._DieuKienSuDung;
			}
			set
			{
				if ((this._DieuKienSuDung != value))
				{
					this.OnDieuKienSuDungChanging(value);
					this.SendPropertyChanging();
					this._DieuKienSuDung = value;
					this.SendPropertyChanged("DieuKienSuDung");
					this.OnDieuKienSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(2000)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_d_Quydinh", Storage="_d_Thanhphan", ThisKey="IDThanhphan", OtherKey="IDThanhphan", IsForeignKey=true)]
		public d_Thanhphan d_Thanhphan
		{
			get
			{
				return this._d_Thanhphan.Entity;
			}
			set
			{
				d_Thanhphan previousValue = this._d_Thanhphan.Entity;
				if (((previousValue != value) 
							|| (this._d_Thanhphan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Thanhphan.Entity = null;
						previousValue.d_Quydinhs.Remove(this);
					}
					this._d_Thanhphan.Entity = value;
					if ((value != null))
					{
						value.d_Quydinhs.Add(this);
						this._IDThanhphan = value.IDThanhphan;
					}
					else
					{
						this._IDThanhphan = default(int);
					}
					this.SendPropertyChanged("d_Thanhphan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_Thanhphan")]
	public partial class d_Thanhphan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDThanhphan;
		
		private string _Ten_INN;
		
		private string _Ten_INCI;
		
		private string _Ten_IUPAC;
		
		private string _CAS_No;
		
		private string _CongThucHoaHoc;
		
		private string _KhoiLuongPhanTu;
		
		private string _CauTrucPhanTu;
		
		private string _TinhChatVatLy;
		
		private string _MoTa;
		
		private string _BaoQuan;
		
		private string _ChatLienQuan;
		
		private string _TLTK;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private string _Ungdung;
		
		private string _Tuongky;
		
		private EntitySet<r_Thanhphan_EWGScore> _r_Thanhphan_EWGScores;
		
		private EntitySet<d_Quydinh> _d_Quydinhs;
		
		private EntitySet<r_Chatlienquan> _r_Chatlienquans;
		
		private EntitySet<r_Thanhphan_Chucnang> _r_Thanhphan_Chucnangs;
		
		private EntitySet<r_Thanhphan_Dangbaoche> _r_Thanhphan_Dangbaoches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDThanhphanChanging(int value);
    partial void OnIDThanhphanChanged();
    partial void OnTen_INNChanging(string value);
    partial void OnTen_INNChanged();
    partial void OnTen_INCIChanging(string value);
    partial void OnTen_INCIChanged();
    partial void OnTen_IUPACChanging(string value);
    partial void OnTen_IUPACChanged();
    partial void OnCAS_NoChanging(string value);
    partial void OnCAS_NoChanged();
    partial void OnCongThucHoaHocChanging(string value);
    partial void OnCongThucHoaHocChanged();
    partial void OnKhoiLuongPhanTuChanging(string value);
    partial void OnKhoiLuongPhanTuChanged();
    partial void OnCauTrucPhanTuChanging(string value);
    partial void OnCauTrucPhanTuChanged();
    partial void OnTinhChatVatLyChanging(string value);
    partial void OnTinhChatVatLyChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnBaoQuanChanging(string value);
    partial void OnBaoQuanChanged();
    partial void OnChatLienQuanChanging(string value);
    partial void OnChatLienQuanChanged();
    partial void OnTLTKChanging(string value);
    partial void OnTLTKChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnUngdungChanging(string value);
    partial void OnUngdungChanged();
    partial void OnTuongkyChanging(string value);
    partial void OnTuongkyChanged();
    #endregion
		
		public d_Thanhphan()
		{
			this._r_Thanhphan_EWGScores = new EntitySet<r_Thanhphan_EWGScore>(new Action<r_Thanhphan_EWGScore>(this.attach_r_Thanhphan_EWGScores), new Action<r_Thanhphan_EWGScore>(this.detach_r_Thanhphan_EWGScores));
			this._d_Quydinhs = new EntitySet<d_Quydinh>(new Action<d_Quydinh>(this.attach_d_Quydinhs), new Action<d_Quydinh>(this.detach_d_Quydinhs));
			this._r_Chatlienquans = new EntitySet<r_Chatlienquan>(new Action<r_Chatlienquan>(this.attach_r_Chatlienquans), new Action<r_Chatlienquan>(this.detach_r_Chatlienquans));
			this._r_Thanhphan_Chucnangs = new EntitySet<r_Thanhphan_Chucnang>(new Action<r_Thanhphan_Chucnang>(this.attach_r_Thanhphan_Chucnangs), new Action<r_Thanhphan_Chucnang>(this.detach_r_Thanhphan_Chucnangs));
			this._r_Thanhphan_Dangbaoches = new EntitySet<r_Thanhphan_Dangbaoche>(new Action<r_Thanhphan_Dangbaoche>(this.attach_r_Thanhphan_Dangbaoches), new Action<r_Thanhphan_Dangbaoche>(this.detach_r_Thanhphan_Dangbaoches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDThanhphan
		{
			get
			{
				return this._IDThanhphan;
			}
			set
			{
				if ((this._IDThanhphan != value))
				{
					this.OnIDThanhphanChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphan = value;
					this.SendPropertyChanged("IDThanhphan");
					this.OnIDThanhphanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_INN", DbType="VarChar(255)")]
		public string Ten_INN
		{
			get
			{
				return this._Ten_INN;
			}
			set
			{
				if ((this._Ten_INN != value))
				{
					this.OnTen_INNChanging(value);
					this.SendPropertyChanging();
					this._Ten_INN = value;
					this.SendPropertyChanged("Ten_INN");
					this.OnTen_INNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_INCI", DbType="VarChar(255)")]
		public string Ten_INCI
		{
			get
			{
				return this._Ten_INCI;
			}
			set
			{
				if ((this._Ten_INCI != value))
				{
					this.OnTen_INCIChanging(value);
					this.SendPropertyChanging();
					this._Ten_INCI = value;
					this.SendPropertyChanged("Ten_INCI");
					this.OnTen_INCIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_IUPAC", DbType="VarChar(255)")]
		public string Ten_IUPAC
		{
			get
			{
				return this._Ten_IUPAC;
			}
			set
			{
				if ((this._Ten_IUPAC != value))
				{
					this.OnTen_IUPACChanging(value);
					this.SendPropertyChanging();
					this._Ten_IUPAC = value;
					this.SendPropertyChanged("Ten_IUPAC");
					this.OnTen_IUPACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAS_No", DbType="VarChar(50)")]
		public string CAS_No
		{
			get
			{
				return this._CAS_No;
			}
			set
			{
				if ((this._CAS_No != value))
				{
					this.OnCAS_NoChanging(value);
					this.SendPropertyChanging();
					this._CAS_No = value;
					this.SendPropertyChanged("CAS_No");
					this.OnCAS_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongThucHoaHoc", DbType="VarChar(255)")]
		public string CongThucHoaHoc
		{
			get
			{
				return this._CongThucHoaHoc;
			}
			set
			{
				if ((this._CongThucHoaHoc != value))
				{
					this.OnCongThucHoaHocChanging(value);
					this.SendPropertyChanging();
					this._CongThucHoaHoc = value;
					this.SendPropertyChanged("CongThucHoaHoc");
					this.OnCongThucHoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiLuongPhanTu", DbType="VarChar(255)")]
		public string KhoiLuongPhanTu
		{
			get
			{
				return this._KhoiLuongPhanTu;
			}
			set
			{
				if ((this._KhoiLuongPhanTu != value))
				{
					this.OnKhoiLuongPhanTuChanging(value);
					this.SendPropertyChanging();
					this._KhoiLuongPhanTu = value;
					this.SendPropertyChanged("KhoiLuongPhanTu");
					this.OnKhoiLuongPhanTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauTrucPhanTu", DbType="VarChar(255)")]
		public string CauTrucPhanTu
		{
			get
			{
				return this._CauTrucPhanTu;
			}
			set
			{
				if ((this._CauTrucPhanTu != value))
				{
					this.OnCauTrucPhanTuChanging(value);
					this.SendPropertyChanging();
					this._CauTrucPhanTu = value;
					this.SendPropertyChanged("CauTrucPhanTu");
					this.OnCauTrucPhanTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhChatVatLy", DbType="NVarChar(2000)")]
		public string TinhChatVatLy
		{
			get
			{
				return this._TinhChatVatLy;
			}
			set
			{
				if ((this._TinhChatVatLy != value))
				{
					this.OnTinhChatVatLyChanging(value);
					this.SendPropertyChanging();
					this._TinhChatVatLy = value;
					this.SendPropertyChanged("TinhChatVatLy");
					this.OnTinhChatVatLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(2000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoQuan", DbType="NVarChar(2000)")]
		public string BaoQuan
		{
			get
			{
				return this._BaoQuan;
			}
			set
			{
				if ((this._BaoQuan != value))
				{
					this.OnBaoQuanChanging(value);
					this.SendPropertyChanging();
					this._BaoQuan = value;
					this.SendPropertyChanged("BaoQuan");
					this.OnBaoQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatLienQuan", DbType="NVarChar(2000)")]
		public string ChatLienQuan
		{
			get
			{
				return this._ChatLienQuan;
			}
			set
			{
				if ((this._ChatLienQuan != value))
				{
					this.OnChatLienQuanChanging(value);
					this.SendPropertyChanging();
					this._ChatLienQuan = value;
					this.SendPropertyChanged("ChatLienQuan");
					this.OnChatLienQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLTK", DbType="NVarChar(2000)")]
		public string TLTK
		{
			get
			{
				return this._TLTK;
			}
			set
			{
				if ((this._TLTK != value))
				{
					this.OnTLTKChanging(value);
					this.SendPropertyChanging();
					this._TLTK = value;
					this.SendPropertyChanged("TLTK");
					this.OnTLTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ungdung", DbType="NVarChar(2000)")]
		public string Ungdung
		{
			get
			{
				return this._Ungdung;
			}
			set
			{
				if ((this._Ungdung != value))
				{
					this.OnUngdungChanging(value);
					this.SendPropertyChanging();
					this._Ungdung = value;
					this.SendPropertyChanged("Ungdung");
					this.OnUngdungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuongky", DbType="NVarChar(2000)")]
		public string Tuongky
		{
			get
			{
				return this._Tuongky;
			}
			set
			{
				if ((this._Tuongky != value))
				{
					this.OnTuongkyChanging(value);
					this.SendPropertyChanging();
					this._Tuongky = value;
					this.SendPropertyChanged("Tuongky");
					this.OnTuongkyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_r_Thanhphan_EWGScore", Storage="_r_Thanhphan_EWGScores", ThisKey="IDThanhphan", OtherKey="IDThanhphan")]
		public EntitySet<r_Thanhphan_EWGScore> r_Thanhphan_EWGScores
		{
			get
			{
				return this._r_Thanhphan_EWGScores;
			}
			set
			{
				this._r_Thanhphan_EWGScores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_d_Quydinh", Storage="_d_Quydinhs", ThisKey="IDThanhphan", OtherKey="IDThanhphan")]
		public EntitySet<d_Quydinh> d_Quydinhs
		{
			get
			{
				return this._d_Quydinhs;
			}
			set
			{
				this._d_Quydinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_r_Chatlienquan", Storage="_r_Chatlienquans", ThisKey="IDThanhphan", OtherKey="IDThanhphan")]
		public EntitySet<r_Chatlienquan> r_Chatlienquans
		{
			get
			{
				return this._r_Chatlienquans;
			}
			set
			{
				this._r_Chatlienquans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_r_Thanhphan_Chucnang", Storage="_r_Thanhphan_Chucnangs", ThisKey="IDThanhphan", OtherKey="IDThanhphan")]
		public EntitySet<r_Thanhphan_Chucnang> r_Thanhphan_Chucnangs
		{
			get
			{
				return this._r_Thanhphan_Chucnangs;
			}
			set
			{
				this._r_Thanhphan_Chucnangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_r_Thanhphan_Dangbaoche", Storage="_r_Thanhphan_Dangbaoches", ThisKey="IDThanhphan", OtherKey="IDThanhphan")]
		public EntitySet<r_Thanhphan_Dangbaoche> r_Thanhphan_Dangbaoches
		{
			get
			{
				return this._r_Thanhphan_Dangbaoches;
			}
			set
			{
				this._r_Thanhphan_Dangbaoches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_r_Thanhphan_EWGScores(r_Thanhphan_EWGScore entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = this;
		}
		
		private void detach_r_Thanhphan_EWGScores(r_Thanhphan_EWGScore entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = null;
		}
		
		private void attach_d_Quydinhs(d_Quydinh entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = this;
		}
		
		private void detach_d_Quydinhs(d_Quydinh entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = null;
		}
		
		private void attach_r_Chatlienquans(r_Chatlienquan entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = this;
		}
		
		private void detach_r_Chatlienquans(r_Chatlienquan entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = null;
		}
		
		private void attach_r_Thanhphan_Chucnangs(r_Thanhphan_Chucnang entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = this;
		}
		
		private void detach_r_Thanhphan_Chucnangs(r_Thanhphan_Chucnang entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = null;
		}
		
		private void attach_r_Thanhphan_Dangbaoches(r_Thanhphan_Dangbaoche entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = this;
		}
		
		private void detach_r_Thanhphan_Dangbaoches(r_Thanhphan_Dangbaoche entity)
		{
			this.SendPropertyChanging();
			entity.d_Thanhphan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.r_Chatlienquan")]
	public partial class r_Chatlienquan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDChatlienquan;
		
		private int _IDThanhphan;
		
		private int _IDThanhphanLienquan;
		
		private EntityRef<d_Thanhphan> _d_Thanhphan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChatlienquanChanging(int value);
    partial void OnIDChatlienquanChanged();
    partial void OnIDThanhphanChanging(int value);
    partial void OnIDThanhphanChanged();
    partial void OnIDThanhphanLienquanChanging(int value);
    partial void OnIDThanhphanLienquanChanged();
    #endregion
		
		public r_Chatlienquan()
		{
			this._d_Thanhphan = default(EntityRef<d_Thanhphan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChatlienquan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDChatlienquan
		{
			get
			{
				return this._IDChatlienquan;
			}
			set
			{
				if ((this._IDChatlienquan != value))
				{
					this.OnIDChatlienquanChanging(value);
					this.SendPropertyChanging();
					this._IDChatlienquan = value;
					this.SendPropertyChanged("IDChatlienquan");
					this.OnIDChatlienquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphan", DbType="Int NOT NULL")]
		public int IDThanhphan
		{
			get
			{
				return this._IDThanhphan;
			}
			set
			{
				if ((this._IDThanhphan != value))
				{
					if (this._d_Thanhphan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDThanhphanChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphan = value;
					this.SendPropertyChanged("IDThanhphan");
					this.OnIDThanhphanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphanLienquan", DbType="Int NOT NULL")]
		public int IDThanhphanLienquan
		{
			get
			{
				return this._IDThanhphanLienquan;
			}
			set
			{
				if ((this._IDThanhphanLienquan != value))
				{
					this.OnIDThanhphanLienquanChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphanLienquan = value;
					this.SendPropertyChanged("IDThanhphanLienquan");
					this.OnIDThanhphanLienquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_r_Chatlienquan", Storage="_d_Thanhphan", ThisKey="IDThanhphan", OtherKey="IDThanhphan", IsForeignKey=true)]
		public d_Thanhphan d_Thanhphan
		{
			get
			{
				return this._d_Thanhphan.Entity;
			}
			set
			{
				d_Thanhphan previousValue = this._d_Thanhphan.Entity;
				if (((previousValue != value) 
							|| (this._d_Thanhphan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Thanhphan.Entity = null;
						previousValue.r_Chatlienquans.Remove(this);
					}
					this._d_Thanhphan.Entity = value;
					if ((value != null))
					{
						value.r_Chatlienquans.Add(this);
						this._IDThanhphan = value.IDThanhphan;
					}
					else
					{
						this._IDThanhphan = default(int);
					}
					this.SendPropertyChanged("d_Thanhphan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.r_Thanhphan_Chucnang")]
	public partial class r_Thanhphan_Chucnang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDThanhphan_Chucnang;
		
		private int _IDThanhphan;
		
		private int _IDChucnang;
		
		private EntityRef<d_Chucnang> _d_Chucnang;
		
		private EntityRef<d_Thanhphan> _d_Thanhphan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDThanhphan_ChucnangChanging(int value);
    partial void OnIDThanhphan_ChucnangChanged();
    partial void OnIDThanhphanChanging(int value);
    partial void OnIDThanhphanChanged();
    partial void OnIDChucnangChanging(int value);
    partial void OnIDChucnangChanged();
    #endregion
		
		public r_Thanhphan_Chucnang()
		{
			this._d_Chucnang = default(EntityRef<d_Chucnang>);
			this._d_Thanhphan = default(EntityRef<d_Thanhphan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphan_Chucnang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDThanhphan_Chucnang
		{
			get
			{
				return this._IDThanhphan_Chucnang;
			}
			set
			{
				if ((this._IDThanhphan_Chucnang != value))
				{
					this.OnIDThanhphan_ChucnangChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphan_Chucnang = value;
					this.SendPropertyChanged("IDThanhphan_Chucnang");
					this.OnIDThanhphan_ChucnangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphan", DbType="Int NOT NULL")]
		public int IDThanhphan
		{
			get
			{
				return this._IDThanhphan;
			}
			set
			{
				if ((this._IDThanhphan != value))
				{
					if (this._d_Thanhphan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDThanhphanChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphan = value;
					this.SendPropertyChanged("IDThanhphan");
					this.OnIDThanhphanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChucnang", DbType="Int NOT NULL")]
		public int IDChucnang
		{
			get
			{
				return this._IDChucnang;
			}
			set
			{
				if ((this._IDChucnang != value))
				{
					if (this._d_Chucnang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChucnangChanging(value);
					this.SendPropertyChanging();
					this._IDChucnang = value;
					this.SendPropertyChanged("IDChucnang");
					this.OnIDChucnangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Chucnang_r_Thanhphan_Chucnang", Storage="_d_Chucnang", ThisKey="IDChucnang", OtherKey="IDChucnang", IsForeignKey=true)]
		public d_Chucnang d_Chucnang
		{
			get
			{
				return this._d_Chucnang.Entity;
			}
			set
			{
				d_Chucnang previousValue = this._d_Chucnang.Entity;
				if (((previousValue != value) 
							|| (this._d_Chucnang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Chucnang.Entity = null;
						previousValue.r_Thanhphan_Chucnangs.Remove(this);
					}
					this._d_Chucnang.Entity = value;
					if ((value != null))
					{
						value.r_Thanhphan_Chucnangs.Add(this);
						this._IDChucnang = value.IDChucnang;
					}
					else
					{
						this._IDChucnang = default(int);
					}
					this.SendPropertyChanged("d_Chucnang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_r_Thanhphan_Chucnang", Storage="_d_Thanhphan", ThisKey="IDThanhphan", OtherKey="IDThanhphan", IsForeignKey=true)]
		public d_Thanhphan d_Thanhphan
		{
			get
			{
				return this._d_Thanhphan.Entity;
			}
			set
			{
				d_Thanhphan previousValue = this._d_Thanhphan.Entity;
				if (((previousValue != value) 
							|| (this._d_Thanhphan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Thanhphan.Entity = null;
						previousValue.r_Thanhphan_Chucnangs.Remove(this);
					}
					this._d_Thanhphan.Entity = value;
					if ((value != null))
					{
						value.r_Thanhphan_Chucnangs.Add(this);
						this._IDThanhphan = value.IDThanhphan;
					}
					else
					{
						this._IDThanhphan = default(int);
					}
					this.SendPropertyChanged("d_Thanhphan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.r_Thanhphan_Dangbaoche")]
	public partial class r_Thanhphan_Dangbaoche : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDThanhphan_Dangbaoche;
		
		private int _IDThanhphan;
		
		private int _IDDangbaoche;
		
		private EntityRef<d_Dangbaoche> _d_Dangbaoche;
		
		private EntityRef<d_Thanhphan> _d_Thanhphan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDThanhphan_DangbaocheChanging(int value);
    partial void OnIDThanhphan_DangbaocheChanged();
    partial void OnIDThanhphanChanging(int value);
    partial void OnIDThanhphanChanged();
    partial void OnIDDangbaocheChanging(int value);
    partial void OnIDDangbaocheChanged();
    #endregion
		
		public r_Thanhphan_Dangbaoche()
		{
			this._d_Dangbaoche = default(EntityRef<d_Dangbaoche>);
			this._d_Thanhphan = default(EntityRef<d_Thanhphan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphan_Dangbaoche", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDThanhphan_Dangbaoche
		{
			get
			{
				return this._IDThanhphan_Dangbaoche;
			}
			set
			{
				if ((this._IDThanhphan_Dangbaoche != value))
				{
					this.OnIDThanhphan_DangbaocheChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphan_Dangbaoche = value;
					this.SendPropertyChanged("IDThanhphan_Dangbaoche");
					this.OnIDThanhphan_DangbaocheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThanhphan", DbType="Int NOT NULL")]
		public int IDThanhphan
		{
			get
			{
				return this._IDThanhphan;
			}
			set
			{
				if ((this._IDThanhphan != value))
				{
					if (this._d_Thanhphan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDThanhphanChanging(value);
					this.SendPropertyChanging();
					this._IDThanhphan = value;
					this.SendPropertyChanged("IDThanhphan");
					this.OnIDThanhphanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDangbaoche", DbType="Int NOT NULL")]
		public int IDDangbaoche
		{
			get
			{
				return this._IDDangbaoche;
			}
			set
			{
				if ((this._IDDangbaoche != value))
				{
					if (this._d_Dangbaoche.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDangbaocheChanging(value);
					this.SendPropertyChanging();
					this._IDDangbaoche = value;
					this.SendPropertyChanged("IDDangbaoche");
					this.OnIDDangbaocheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Dangbaoche_r_Thanhphan_Dangbaoche", Storage="_d_Dangbaoche", ThisKey="IDDangbaoche", OtherKey="IDDangbaoche", IsForeignKey=true)]
		public d_Dangbaoche d_Dangbaoche
		{
			get
			{
				return this._d_Dangbaoche.Entity;
			}
			set
			{
				d_Dangbaoche previousValue = this._d_Dangbaoche.Entity;
				if (((previousValue != value) 
							|| (this._d_Dangbaoche.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Dangbaoche.Entity = null;
						previousValue.r_Thanhphan_Dangbaoches.Remove(this);
					}
					this._d_Dangbaoche.Entity = value;
					if ((value != null))
					{
						value.r_Thanhphan_Dangbaoches.Add(this);
						this._IDDangbaoche = value.IDDangbaoche;
					}
					else
					{
						this._IDDangbaoche = default(int);
					}
					this.SendPropertyChanged("d_Dangbaoche");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thanhphan_r_Thanhphan_Dangbaoche", Storage="_d_Thanhphan", ThisKey="IDThanhphan", OtherKey="IDThanhphan", IsForeignKey=true)]
		public d_Thanhphan d_Thanhphan
		{
			get
			{
				return this._d_Thanhphan.Entity;
			}
			set
			{
				d_Thanhphan previousValue = this._d_Thanhphan.Entity;
				if (((previousValue != value) 
							|| (this._d_Thanhphan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Thanhphan.Entity = null;
						previousValue.r_Thanhphan_Dangbaoches.Remove(this);
					}
					this._d_Thanhphan.Entity = value;
					if ((value != null))
					{
						value.r_Thanhphan_Dangbaoches.Add(this);
						this._IDThanhphan = value.IDThanhphan;
					}
					else
					{
						this._IDThanhphan = default(int);
					}
					this.SendPropertyChanged("d_Thanhphan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
